packages:
  - 'packages/*'
  - 'naveditor'
  - 'naveditor-lib'
  - 'naveditor-web'
  - 'naveditor-desktop'
  - 'naveditor-terminal'

catalog:
  # Runtime dependencies
  commander: ^14.0.3
  effect: ^3.19.17
  ink: ^6.7.0
  ink-select-input: ^6.2.0
  ink-web: ^0.1.11
  react: ^19.2.4
  react-dom: ^19.2.4
  tinybase: ^7.3.4
  zod: ^4.3.6
  '@xterm/xterm': ^6.0.0
  '@sqlite.org/sqlite-wasm': 3.51.2-build6
  '@tauri-apps/api': ^2.10.1
  
  '@inkjs/ui': ^2.0.0
  '@inrupt/vocab-common-rdf': ^1.0.5
  '@inrupt/vocab-solid-common': ^0.7.5

  # Dev dependencies
  '@types/node': ^25.2.3
  '@types/react': ^19.2.14
  '@types/react-dom': ^19.2.3
  typescript: ^5.9.3
  vite: ^7.3.1
  '@vitejs/plugin-react': ^5.1.4
  'vite-plugin-node-polyfills': ^0.25.0
  tsx: ^4.21.0
  vitest: ^4.0.18
